version: "3.9"

services:
  jenkins:
    build: ./controller
    container_name: jenkins-controller
    ports:
      - "8080:8080"
    environment:
      - JENKINS_ADMIN_PASS=admin123
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./casc/jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml:ro
    depends_on:
      - agent-ubuntu
      - agent-debian

  agent-ubuntu:
    build: ./agents/ubuntu-agent
    container_name: agent-ubuntu
    hostname: agent-ubuntu
    expose:
      - "22"

  agent-debian:
    build: ./agents/debian-agent
    container_name: agent-debian
    hostname: agent-debian
    expose:
      - "22"

volumes:
  jenkins_home:
